import type { Rank, AdventureType } from "@/generated/prisma/enums";

export type SeedAdventure = {
  rank: Rank;
  name: string;
  type: AdventureType;
  sortOrder: number;
  note?: string;
};

/**
 * Transcribed directly from Master - Pack 376 Advancement Tracker.xlsx (one sheet
 * per rank, Adventure/Type columns). 6 required adventures + electives per rank,
 * 2+ electives needed to earn the rank (uniform across all 6 ranks in that sheet).
 */
export const SEED_ADVENTURES: SeedAdventure[] = [
  // --- Lion ---
  { rank: "LION", name: "Bobcat", type: "REQUIRED", sortOrder: 1 },
  { rank: "LION", name: "Mountain Lion", type: "REQUIRED", sortOrder: 2 },
  { rank: "LION", name: "Fun on the Run", type: "REQUIRED", sortOrder: 3 },
  { rank: "LION", name: "King of the Jungle", type: "REQUIRED", sortOrder: 4 },
  { rank: "LION", name: "Lion's Roar", type: "REQUIRED", sortOrder: 5 },
  { rank: "LION", name: "Lion's Pride", type: "REQUIRED", sortOrder: 6 },
  { rank: "LION", name: "Archery*", type: "ELECTIVE", sortOrder: 7,
    note: "Requires a council-supported activity (Family Adventure Camp, Cub Scout Summer Camp, or Day Camp) with certified instructors." },
  { rank: "LION", name: "Build It Up, Knock It Down", type: "ELECTIVE", sortOrder: 8 },
  { rank: "LION", name: "Champions for Nature", type: "ELECTIVE", sortOrder: 9 },
  { rank: "LION", name: "Count on Me", type: "ELECTIVE", sortOrder: 10 },
  { rank: "LION", name: "Everyday Tech", type: "ELECTIVE", sortOrder: 11 },
  { rank: "LION", name: "Gizmos & Gadgets", type: "ELECTIVE", sortOrder: 12 },
  { rank: "LION", name: "Go Fish", type: "ELECTIVE", sortOrder: 13 },
  { rank: "LION", name: "I'll Do It Myself", type: "ELECTIVE", sortOrder: 14 },
  { rank: "LION", name: "Let's Camp", type: "ELECTIVE", sortOrder: 15 },
  { rank: "LION", name: "On A Roll", type: "ELECTIVE", sortOrder: 16 },
  { rank: "LION", name: "On Your Mark", type: "ELECTIVE", sortOrder: 17 },
  { rank: "LION", name: "Pick My Path", type: "ELECTIVE", sortOrder: 18 },
  { rank: "LION", name: "Race Time", type: "ELECTIVE", sortOrder: 19 },
  { rank: "LION", name: "Ready, Set, Grow", type: "ELECTIVE", sortOrder: 20 },
  { rank: "LION", name: "Slingshot*", type: "ELECTIVE", sortOrder: 21,
    note: "Requires a council-supported activity (Family Adventure Camp, Cub Scout Summer Camp, or Day Camp) with certified instructors." },
  { rank: "LION", name: "Time to Swim", type: "ELECTIVE", sortOrder: 22 },
  // --- Tiger ---
  { rank: "TIGER", name: "Bobcat", type: "REQUIRED", sortOrder: 1 },
  { rank: "TIGER", name: "Tigers in the Wild", type: "REQUIRED", sortOrder: 2 },
  { rank: "TIGER", name: "Tiger Bites", type: "REQUIRED", sortOrder: 3 },
  { rank: "TIGER", name: "Team Tiger", type: "REQUIRED", sortOrder: 4 },
  { rank: "TIGER", name: "Tiger's Roar", type: "REQUIRED", sortOrder: 5 },
  { rank: "TIGER", name: "Tiger Circles", type: "REQUIRED", sortOrder: 6 },
  { rank: "TIGER", name: "Archery*", type: "ELECTIVE", sortOrder: 7,
    note: "Requires a council-supported activity (Family Adventure Camp, Cub Scout Summer Camp, or Day Camp) with certified instructors." },
  { rank: "TIGER", name: "BB Gun*", type: "ELECTIVE", sortOrder: 8,
    note: "Requires a council-supported activity (Family Adventure Camp, Cub Scout Summer Camp, or Day Camp) with certified instructors." },
  { rank: "TIGER", name: "Champions for Nature", type: "ELECTIVE", sortOrder: 9 },
  { rank: "TIGER", name: "Curiosity, Intrigue, and Magical Mysteries", type: "ELECTIVE", sortOrder: 10 },
  { rank: "TIGER", name: "Designed by Tiger", type: "ELECTIVE", sortOrder: 11 },
  { rank: "TIGER", name: "Fish On", type: "ELECTIVE", sortOrder: 12 },
  { rank: "TIGER", name: "Floats and Boats", type: "ELECTIVE", sortOrder: 13 },
  { rank: "TIGER", name: "Good Knights", type: "ELECTIVE", sortOrder: 14 },
  { rank: "TIGER", name: "Let's Camp", type: "ELECTIVE", sortOrder: 15 },
  { rank: "TIGER", name: "Race Time", type: "ELECTIVE", sortOrder: 16 },
  { rank: "TIGER", name: "Rolling Tigers", type: "ELECTIVE", sortOrder: 17 },
  { rank: "TIGER", name: "Safe and Smart", type: "ELECTIVE", sortOrder: 18 },
  { rank: "TIGER", name: "Slingshot*", type: "ELECTIVE", sortOrder: 19,
    note: "Requires a council-supported activity (Family Adventure Camp, Cub Scout Summer Camp, or Day Camp) with certified instructors." },
  { rank: "TIGER", name: "Sky Is the Limit", type: "ELECTIVE", sortOrder: 20 },
  { rank: "TIGER", name: "Stories in Shapes", type: "ELECTIVE", sortOrder: 21 },
  { rank: "TIGER", name: "Summertime Fun", type: "ELECTIVE", sortOrder: 22 },
  { rank: "TIGER", name: "Tech All Around", type: "ELECTIVE", sortOrder: 23 },
  { rank: "TIGER", name: "Tiger Tag", type: "ELECTIVE", sortOrder: 24 },
  { rank: "TIGER", name: "Tiger-iffic!", type: "ELECTIVE", sortOrder: 25 },
  { rank: "TIGER", name: "Tigers in the Water", type: "ELECTIVE", sortOrder: 26 },
  // --- Wolf ---
  { rank: "WOLF", name: "Bobcat", type: "REQUIRED", sortOrder: 1 },
  { rank: "WOLF", name: "Paws on the Path", type: "REQUIRED", sortOrder: 2 },
  { rank: "WOLF", name: "Running with the Pack", type: "REQUIRED", sortOrder: 3 },
  { rank: "WOLF", name: "Council Fire", type: "REQUIRED", sortOrder: 4 },
  { rank: "WOLF", name: "Safety in Numbers", type: "REQUIRED", sortOrder: 5 },
  { rank: "WOLF", name: "Footsteps", type: "REQUIRED", sortOrder: 6 },
  { rank: "WOLF", name: "A Wolf Goes Fishing", type: "ELECTIVE", sortOrder: 7 },
  { rank: "WOLF", name: "Adventures in Coins", type: "ELECTIVE", sortOrder: 8 },
  { rank: "WOLF", name: "Air of the Wolf", type: "ELECTIVE", sortOrder: 9 },
  { rank: "WOLF", name: "Archery*", type: "ELECTIVE", sortOrder: 10,
    note: "Requires a council-supported activity (Family Adventure Camp, Cub Scout Summer Camp, or Day Camp) with certified instructors." },
  { rank: "WOLF", name: "BB Gun*", type: "ELECTIVE", sortOrder: 11,
    note: "Requires a council-supported activity (Family Adventure Camp, Cub Scout Summer Camp, or Day Camp) with certified instructors." },
  { rank: "WOLF", name: "Champions for Nature", type: "ELECTIVE", sortOrder: 12 },
  { rank: "WOLF", name: "Code of the Wolf", type: "ELECTIVE", sortOrder: 13 },
  { rank: "WOLF", name: "Computing Wolves", type: "ELECTIVE", sortOrder: 14 },
  { rank: "WOLF", name: "Cubs Who Care", type: "ELECTIVE", sortOrder: 15 },
  { rank: "WOLF", name: "Digging in the Past", type: "ELECTIVE", sortOrder: 16 },
  { rank: "WOLF", name: "Finding Your Way", type: "ELECTIVE", sortOrder: 17 },
  { rank: "WOLF", name: "Germs Alive!", type: "ELECTIVE", sortOrder: 18 },
  { rank: "WOLF", name: "Let's Camp", type: "ELECTIVE", sortOrder: 19 },
  { rank: "WOLF", name: "Paws for Water", type: "ELECTIVE", sortOrder: 20 },
  { rank: "WOLF", name: "Paws of Skills", type: "ELECTIVE", sortOrder: 21 },
  { rank: "WOLF", name: "Pedal With the Pack", type: "ELECTIVE", sortOrder: 22 },
  { rank: "WOLF", name: "Race Time", type: "ELECTIVE", sortOrder: 23 },
  { rank: "WOLF", name: "Slingshot*", type: "ELECTIVE", sortOrder: 24,
    note: "Requires a council-supported activity (Family Adventure Camp, Cub Scout Summer Camp, or Day Camp) with certified instructors." },
  { rank: "WOLF", name: "Spirit of the Water", type: "ELECTIVE", sortOrder: 25 },
  { rank: "WOLF", name: "Summertime Fun", type: "ELECTIVE", sortOrder: 26 },
  // --- Bear ---
  { rank: "BEAR", name: "Bobcat", type: "REQUIRED", sortOrder: 1 },
  { rank: "BEAR", name: "Bear Habitat", type: "REQUIRED", sortOrder: 2 },
  { rank: "BEAR", name: "Bear Strong", type: "REQUIRED", sortOrder: 3 },
  { rank: "BEAR", name: "Paws for Action", type: "REQUIRED", sortOrder: 4 },
  { rank: "BEAR", name: "Standing Tall", type: "REQUIRED", sortOrder: 5 },
  { rank: "BEAR", name: "Fellowship", type: "REQUIRED", sortOrder: 6 },
  { rank: "BEAR", name: "A Bear Goes Fishing", type: "ELECTIVE", sortOrder: 7 },
  { rank: "BEAR", name: "Archery*", type: "ELECTIVE", sortOrder: 8,
    note: "Requires a council-supported activity (Family Adventure Camp, Cub Scout Summer Camp, or Day Camp) with certified instructors." },
  { rank: "BEAR", name: "Balancing Bears", type: "ELECTIVE", sortOrder: 9 },
  { rank: "BEAR", name: "Baloo the Builder", type: "ELECTIVE", sortOrder: 10 },
  { rank: "BEAR", name: "BB Gun*", type: "ELECTIVE", sortOrder: 11,
    note: "Requires a council-supported activity (Family Adventure Camp, Cub Scout Summer Camp, or Day Camp) with certified instructors." },
  { rank: "BEAR", name: "Bears Afloat", type: "ELECTIVE", sortOrder: 12 },
  { rank: "BEAR", name: "Bears on Bikes", type: "ELECTIVE", sortOrder: 13 },
  { rank: "BEAR", name: "Champions for Nature", type: "ELECTIVE", sortOrder: 14 },
  { rank: "BEAR", name: "Chef Tech", type: "ELECTIVE", sortOrder: 15 },
  { rank: "BEAR", name: "Critter Care", type: "ELECTIVE", sortOrder: 16 },
  { rank: "BEAR", name: "Forensics", type: "ELECTIVE", sortOrder: 17 },
  { rank: "BEAR", name: "Let's Camp", type: "ELECTIVE", sortOrder: 18 },
  { rank: "BEAR", name: "Marble Madness", type: "ELECTIVE", sortOrder: 19 },
  { rank: "BEAR", name: "Race Time", type: "ELECTIVE", sortOrder: 20 },
  { rank: "BEAR", name: "Roaring Laughter", type: "ELECTIVE", sortOrder: 21 },
  { rank: "BEAR", name: "Salmon Run", type: "ELECTIVE", sortOrder: 22 },
  { rank: "BEAR", name: "Slingshot*", type: "ELECTIVE", sortOrder: 23,
    note: "Requires a council-supported activity (Family Adventure Camp, Cub Scout Summer Camp, or Day Camp) with certified instructors." },
  { rank: "BEAR", name: "Summertime Fun", type: "ELECTIVE", sortOrder: 24 },
  { rank: "BEAR", name: "Super Science", type: "ELECTIVE", sortOrder: 25 },
  { rank: "BEAR", name: "Whittling", type: "ELECTIVE", sortOrder: 26 },
  // --- Webelos ---
  { rank: "WEBELOS", name: "Bobcat", type: "REQUIRED", sortOrder: 1 },
  { rank: "WEBELOS", name: "Webelos Walkabout", type: "REQUIRED", sortOrder: 2 },
  { rank: "WEBELOS", name: "Stronger, Faster, Higher", type: "REQUIRED", sortOrder: 3 },
  { rank: "WEBELOS", name: "My Community", type: "REQUIRED", sortOrder: 4 },
  { rank: "WEBELOS", name: "My Safety", type: "REQUIRED", sortOrder: 5 },
  { rank: "WEBELOS", name: "My Family", type: "REQUIRED", sortOrder: 6 },
  { rank: "WEBELOS", name: "Aquanaut", type: "ELECTIVE", sortOrder: 7 },
  { rank: "WEBELOS", name: "Archery*", type: "ELECTIVE", sortOrder: 8,
    note: "Requires a council-supported activity (Family Adventure Camp, Cub Scout Summer Camp, or Day Camp) with certified instructors." },
  { rank: "WEBELOS", name: "Art Explosion", type: "ELECTIVE", sortOrder: 9 },
  { rank: "WEBELOS", name: "Aware and Care", type: "ELECTIVE", sortOrder: 10 },
  { rank: "WEBELOS", name: "BB Gun*", type: "ELECTIVE", sortOrder: 11,
    note: "Requires a council-supported activity (Family Adventure Camp, Cub Scout Summer Camp, or Day Camp) with certified instructors." },
  { rank: "WEBELOS", name: "Build It", type: "ELECTIVE", sortOrder: 12 },
  { rank: "WEBELOS", name: "Catch the Big One", type: "ELECTIVE", sortOrder: 13 },
  { rank: "WEBELOS", name: "Champions for Nature", type: "ELECTIVE", sortOrder: 14 },
  { rank: "WEBELOS", name: "Chef's Knife", type: "ELECTIVE", sortOrder: 15 },
  { rank: "WEBELOS", name: "Earth Rocks!", type: "ELECTIVE", sortOrder: 16 },
  { rank: "WEBELOS", name: "Let's Camp", type: "ELECTIVE", sortOrder: 17 },
  { rank: "WEBELOS", name: "Math on the Trail", type: "ELECTIVE", sortOrder: 18 },
  { rank: "WEBELOS", name: "Modular Design", type: "ELECTIVE", sortOrder: 19 },
  { rank: "WEBELOS", name: "Paddle Onward", type: "ELECTIVE", sortOrder: 20 },
  { rank: "WEBELOS", name: "Pedal Away", type: "ELECTIVE", sortOrder: 21 },
  { rank: "WEBELOS", name: "Race Time", type: "ELECTIVE", sortOrder: 22 },
  { rank: "WEBELOS", name: "Slingshot*", type: "ELECTIVE", sortOrder: 23,
    note: "Requires a council-supported activity (Family Adventure Camp, Cub Scout Summer Camp, or Day Camp) with certified instructors." },
  { rank: "WEBELOS", name: "Summertime Fun", type: "ELECTIVE", sortOrder: 24 },
  { rank: "WEBELOS", name: "Tech on the Trail", type: "ELECTIVE", sortOrder: 25 },
  { rank: "WEBELOS", name: "Yo-Yo", type: "ELECTIVE", sortOrder: 26 },
  // --- Arrow of Light ---
  { rank: "AOL", name: "Bobcat", type: "REQUIRED", sortOrder: 1 },
  { rank: "AOL", name: "Outdoor Adventurer", type: "REQUIRED", sortOrder: 2 },
  { rank: "AOL", name: "Personal Fitness", type: "REQUIRED", sortOrder: 3 },
  { rank: "AOL", name: "Citizenship", type: "REQUIRED", sortOrder: 4 },
  { rank: "AOL", name: "First Aid", type: "REQUIRED", sortOrder: 5 },
  { rank: "AOL", name: "Duty to God", type: "REQUIRED", sortOrder: 6 },
  { rank: "AOL", name: "Archery*", type: "ELECTIVE", sortOrder: 7,
    note: "Requires a council-supported activity (Family Adventure Camp, Cub Scout Summer Camp, or Day Camp) with certified instructors." },
  { rank: "AOL", name: "BB Gun*", type: "ELECTIVE", sortOrder: 8,
    note: "Requires a council-supported activity (Family Adventure Camp, Cub Scout Summer Camp, or Day Camp) with certified instructors." },
  { rank: "AOL", name: "Champions for Nature", type: "ELECTIVE", sortOrder: 9 },
  { rank: "AOL", name: "Cycling", type: "ELECTIVE", sortOrder: 10 },
  { rank: "AOL", name: "Engineer", type: "ELECTIVE", sortOrder: 11 },
  { rank: "AOL", name: "Estimations", type: "ELECTIVE", sortOrder: 12 },
  { rank: "AOL", name: "Fishing", type: "ELECTIVE", sortOrder: 13 },
  { rank: "AOL", name: "High Tech Outdoors", type: "ELECTIVE", sortOrder: 14 },
  { rank: "AOL", name: "Into the Wild", type: "ELECTIVE", sortOrder: 15 },
  { rank: "AOL", name: "Into the Woods", type: "ELECTIVE", sortOrder: 16 },
  { rank: "AOL", name: "Knife Safety", type: "ELECTIVE", sortOrder: 17 },
  { rank: "AOL", name: "Paddle Craft", type: "ELECTIVE", sortOrder: 18 },
  { rank: "AOL", name: "Race Time", type: "ELECTIVE", sortOrder: 19 },
  { rank: "AOL", name: "Slingshot*", type: "ELECTIVE", sortOrder: 20,
    note: "Requires a council-supported activity (Family Adventure Camp, Cub Scout Summer Camp, or Day Camp) with certified instructors." },
  { rank: "AOL", name: "Summertime Fun", type: "ELECTIVE", sortOrder: 21 },
  { rank: "AOL", name: "Swimming", type: "ELECTIVE", sortOrder: 22 },
];
