import { prisma } from "@/lib/prisma";
import { requireAdminSession } from "@/lib/authorize";
import { formatDateOnly, todayDateOnlyString } from "@/lib/dateOnly";
import {
  RECEIPT_KIND_INFO,
  RECEIPT_RECORDS_EMAIL,
  defaultIssuerName,
  formatReceiptMoney,
  receiptDataFromRecord,
} from "@/lib/receipts";
import ReceiptForm from "@/components/ReceiptForm";
import ReceiptDownloadButton from "@/components/ReceiptDownloadButton";
import ReceiptDeleteButton from "@/components/ReceiptDeleteButton";

const HISTORY_LIMIT = 200;

export default async function AdminReceiptsPage() {
  // Admin only. Junior Admin, Committee Member and the rest never see this page.
  const session = await requireAdminSession();

  const [receipts, total] = await Promise.all([
    prisma.receipt.findMany({ orderBy: { createdAt: "desc" }, take: HISTORY_LIMIT }),
    prisma.receipt.count(),
  ]);

  return (
    <>
      <div className="page-head">
        <div>
          <div className="eyebrow">Money</div>
          <h2>Receipts</h2>
        </div>
      </div>

      <ReceiptForm
        today={todayDateOnlyString()}
        defaultIssuerName={defaultIssuerName(session.displayName)}
        defaultIssuerTitle="Committee Chair"
        recordsEmail={RECEIPT_RECORDS_EMAIL}
      />

      <h3 style={{ fontSize: 17, margin: "32px 0 14px" }}>Receipt History</h3>
      <div className="table-scroll">
        <table className="data-table">
          <thead>
            <tr>
              <th>Received from</th>
              <th>Date</th>
              <th>Type</th>
              <th>Amount</th>
              <th>Emailed to</th>
              <th>Generated by</th>
              <th />
            </tr>
          </thead>
          <tbody>
            {receipts.length === 0 && (
              <tr>
                <td colSpan={7}>No receipts yet. Every receipt you download or email will be listed here.</td>
              </tr>
            )}
            {receipts.map((r) => {
              const data = receiptDataFromRecord(r);
              return (
                <tr key={r.id}>
                  <td>{r.receivedFrom}</td>
                  <td data-label="Date">{formatDateOnly(data.date)}</td>
                  <td data-label="Type">{RECEIPT_KIND_INFO[data.kind].label}</td>
                  <td data-label="Amount">{formatReceiptMoney(r.amountCents)}</td>
                  <td data-label="Emailed to">{r.emailedTo ?? "—"}</td>
                  <td data-label="Generated by">{r.issuedByName}</td>
                  <td className="actions">
                    <ReceiptDownloadButton id={r.id} />
                    <ReceiptDeleteButton id={r.id} label={`${r.receivedFrom}, ${formatReceiptMoney(r.amountCents)}`} emailedTo={r.emailedTo} />
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
      {total > HISTORY_LIMIT && (
        <p className="form-note">Showing the latest {HISTORY_LIMIT} of {total} receipts.</p>
      )}
    </>
  );
}
